services:
  app:
    build: ./app
    ports:
      - "1000:1000"
    volumes:
      - ./app/:/app/
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    volumes:
      - ./ganache_data:/ganache_data
    ports:
      - "8545:8545"
    command: --db=/ganache_data --mnemonic 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'