version: '3'
services:
  py_backend:
    build: ./py_backend
    image: py_backend:1.0
    container_name: py_backend
    volumes:
      - ./py_backend/:/py_backend/
    depends_on:
      - ganaches
    env_file:
      - .env
  
  ganaches:
    build: ./ganache
    image: ganaches:1.0
    container_name: ganaches
    volumes:
      - ./ganache:/ganache
    env_file:
      - .env
    ports:
      - "${BASE_PORT}-${TOP_PORT}:${BASE_PORT}-${TOP_PORT}"