services:
  
  py_backend:
    build: ./py_backend
    image: py_backend:1.0
    container_name: py_backend
    volumes:
      - ./py_backend/:/py_backend/
    depends_on:
      - ganaches
    environment:
      - PORTS=${PORTS}
      - BASE_PORT=${BASE_PORT}
      - URL=ws://ganaches:10000
      - POLL_INTERVAL=0.5
      - SOLC_VERSION=0.8.18
      - ADMIN_ADDRESS=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
      - ADMIN_PK=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
  
  ganaches:
    build: ./ganache
    image: ganaches:1.0
    container_name: ganaches
    volumes:
      - ./ganache:/ganache
    environment:
      - PORTS=${PORTS}
      - BASE_PORT=${BASE_PORT}
    ports:
      - "${BASE_PORT}-${TOP_PORT}:${BASE_PORT}-${TOP_PORT}"