services:
  off-chain-elements:
    build: ./off_chain_elements
    ports:
      - "10010:10010"
    volumes:
      - ./off_chain_elements/:/off_chain_elements/
  ganache:
    image: multi_ganache
    container_name: blockchain
    build:
      dockerfile: /ganache_data/Dockerfile
    volumes:
      - ./ganache_data:/ganache_data
    environment:
      - BASE_PORT=10000
      - TOP_PORT=10003
    ports:
      - "${BASE_PORT}-${TOP_PORT}:${BASE_PORT}-${TOP_PORT}"